static const char* particle_update_vs = "#version 330 core\n"
"\n"
"layout (location = 0) in vec3 inPosition; // current particle position\n"
"layout (location = 1) in vec3 inVelocity; // current particle velocity\n"
"layout (location = 2) in float inTTL;       // current particle life\n"
"\n"
"out vec3 outPosition;\n"
"out vec3 outVelocity;\n"
"out float outTTL;\n"
"\n"
"layout (std140) uniform settings\n"
"{\n"
"  vec3  gravity;\n"
"  float deltaTime;\n"
"  vec3  emitterVel;\n"
"  float emitterTTL;\n"
"  vec3  emitterPos;\n"
"  float spawnProbability;\n"
"  vec3  emitterSpread;\n"
"};\n"
"\n"
"// Random number generator between [-1, 1]\n"
"float rand(vec2 co);\n"
"\n"
"void main()\n"
"{\n"
"  float random = rand(vec2(deltaTime * float(gl_VertexID)));\n"
"  if (random > spawnProbability)\n"
"  {\n"
"    // New particle\n"
"    outPosition = emitterPos;\n"
"    outVelocity = emitterVel + emitterSpread *\n"
"      vec3(rand(vec2(float(gl_VertexID + 1.0))) -0.5,\n"
"           rand(vec2(float(gl_VertexID + 2.0))) -0.5,\n"
"           rand(vec2(float(gl_VertexID + 3.0))) -0.5);\n"
"    outTTL = emitterTTL;\n"
"    return;\n"
"  }\n"
"\n"
"  if (inTTL <= 0.0)\n"
"  {\n"
"    // Delete particle\n"
"    outPosition = inPosition;\n"
"    outVelocity = vec3(0.0);\n"
"    outTTL = -1.0;\n"
"    return;\n"
"  }\n"
"\n"
"  // Update particle\n"
"  outTTL = inTTL - deltaTime;\n"
"\n"
"  vec3 processed_velocity = inVelocity;\n"
"  float delta = 0.0;\n"
"\n"
"  vec3 newVelocity = processed_velocity + gravity * deltaTime;\n"
"  vec3 newPosition = inPosition + newVelocity * deltaTime;\n"
"    \n"
"  outVelocity = newVelocity;\n"
"  outPosition = newPosition;\n"
"}\n"
"    \n"
"float rand(vec2 co)\n"
"{\n"
"	return fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453);\n"
"}\n"
;
