static const char* particle_render_vs = "#version 330 core\n"
"\n"
"layout (location = 0) in vec3 inPosition;\n"
"layout (location = 1) in float inTTL;\n"
"\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 projection;\n"
"\n"
"out float drawOrDie;\n"
"\n"
"void main() {\n"
"   \n"
"    if (inTTL < 0.0) {\n"
"        drawOrDie = -1.0;\n"
"    }\n"
"    else {\n"
"        drawOrDie = 1.0;\n"
"    }\n"
"\n"
"    gl_Position = projection * view * model * vec4(inPosition, 1.0);\n"
"    gl_PointSize = 10.0;\n"
"}\n"
;
