static const char* particle_update_gs = "#version 330 core\n"
"\n"
"layout(points) in;\n"
"layout(points, max_vertices = 1) out;\n"
"\n"
"in vec3 outPosition[];\n"
"in vec3 outVelocity[];\n"
"in float outTTL[];\n"
"\n"
"out vec3 geomPosition;\n"
"out vec3 geomVelocity;\n"
"out float geomTTL;\n"
"\n"
"void main() {\n"
"    geomPosition = outPosition[0];\n"
"    geomVelocity = outVelocity[0];\n"
"    geomTTL = outTTL[0];\n"
"\n"
"    EmitVertex();\n"
"    EndPrimitive();\n"
"}\n"
;
