static const char* particle_render_fs = "#version 330 core\n"
"\n"
"in float drawOrDieFrag;\n"
"in vec2 TexCoordFrag;\n"
"\n"
"out vec4 FragColor;\n"
"uniform sampler2D sprite;\n"
"\n"
"void main() {\n"
"\n"
"    if (drawOrDieFrag < 0.0) {\n"
"        discard;\n"
"    }\n"
"    else {\n"
"        FragColor = texture(sprite, TexCoordFrag);\n"
"        if (FragColor.a < 0.1) {\n"
"            discard;\n"
"        }\n"
"        //FragColor = vec4(0.0, 1.0, 0.0, 1.0); // White\n"
"    }\n"
"}\n"
;
