static const char* particle_render_gs = "#version 330 core\n"
"\n"
"layout (points) in;\n"
"layout (triangle_strip, max_vertices = 4) out;\n"
"\n"
"in float drawOrDie[];\n"
"\n"
"uniform int atlas_width;\n"
"uniform int atlas_height;\n"
"uniform int atlas_index;\n"
"uniform float scale = 1.0;\n"
"uniform float aspect_ratio = 1.0;\n"
"\n"
"out vec2 TexCoordFrag;\n"
"out float drawOrDieFrag;\n"
"\n"
"void main()\n"
"{\n"
"  drawOrDieFrag = drawOrDie[0];\n"
"  float square_x = 1.0 / atlas_width;\n"
"  float square_y = 1.0 / atlas_height;\n"
"  int row_index = atlas_index / atlas_width;\n"
"  int col_index = atlas_index % atlas_width;\n"
"\n"
"  float adjusted_scale_x = scale / (aspect_ratio < 1.0 ? aspect_ratio : 1.0);\n"
"  float adjusted_scale_y = scale / (aspect_ratio > 1.0 ? 1.0 / aspect_ratio : 1.0);\n"
"\n"
"  gl_Position = gl_in[0].gl_Position + vec4(-1.0 * adjusted_scale_x,\n"
"                                            -1.0 * adjusted_scale_y, 0.0, 0.0);\n"
"  TexCoordFrag = vec2(square_x * col_index,\n"
"                      square_y * (atlas_height - row_index - 1));\n"
"  EmitVertex();\n"
"  gl_Position = gl_in[0].gl_Position + vec4(1.0 * adjusted_scale_x,\n"
"                                            -1.0 * adjusted_scale_y, 0.0, 0.0);\n"
"  TexCoordFrag = vec2(square_x * (col_index + 1),\n"
"                      square_y * (atlas_height - row_index - 1));\n"
"  EmitVertex();\n"
"  gl_Position = gl_in[0].gl_Position + vec4(-1.0 * adjusted_scale_x,\n"
"                                            1.0 * adjusted_scale_y, 0.0, 0.0);\n"
"  TexCoordFrag = vec2(square_x * col_index,\n"
"                      square_y * (atlas_height - row_index));\n"
"  EmitVertex();\n"
"  gl_Position = gl_in[0].gl_Position + vec4(1.0 * adjusted_scale_x,\n"
"                                            1.0 * adjusted_scale_y, 0.0, 0.0);\n"
"  TexCoordFrag = vec2(square_x * (col_index + 1),\n"
"                      square_y * (atlas_height - row_index));\n"
"  EmitVertex();\n"
"  EndPrimitive();\n"
"}\n"
;
