static const char* phong_vs = "#version 330 core\n"
"layout (location = 0) in vec3 aPos;\n"
"layout (location = 1) in vec3 aNormal;\n"
"layout (location = 2) in vec2 aTexCoords;\n"
"  \n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 projection;\n"
"\n"
"uniform int atlasSize = 4;\n"
"uniform int atlasIndex = 0;\n"
"\n"
"out vec3 Normal;\n"
"out vec3 FragPos; // position of the fragment in world space\n"
"out vec2 TexCoords;\n"
"\n"
"void main()\n"
"{\n"
"  gl_Position = projection * view * model * vec4(aPos, 1.0);\n"
"  // Use this the normal matrix (tranpose of the inverse of the model)\n"
"  // when we have non-uniform scaling\n"
"  Normal = mat3(transpose(inverse(model))) * aNormal;\n"
"  FragPos = vec3(model * vec4(aPos, 1.0));\n"
"\n"
"  // Atlas offset\n"
"  vec2 offset = vec2((1.0 / atlasSize) * (atlasIndex % atlasSize), 0.0);\n"
"  TexCoords = aTexCoords + offset;\n"
"}\n"
;
