static const char* skybox_vs = "#version 330 core\n"
"\n"
"layout (location = 0) in vec3 aPos;\n"
"\n"
"out vec3 TexCoords;\n"
"\n"
"uniform mat4 projection;\n"
"uniform mat4 view;\n"
"\n"
"void main()\n"
"{\n"
"  TexCoords   = aPos;\n"
"  vec4 pos    = projection * view * vec4(aPos, 1.0);\n"
"  gl_Position = pos.xyww;\n"
"}\n"
;
