static const char* default_shader_fs = "#version 330 core\n"
"\n"
"// Structs\n"
"\n"
"struct Material {\n"
"    sampler2D texture_diffuse1;\n"
"    sampler2D texture_specular1;\n"
"    float shininess;\n"
"};\n"
"uniform Material material;\n"
"\n"
"struct DirLight {\n"
"    vec3 direction;\n"
"    vec3 ambient;\n"
"    vec3 diffuse;\n"
"    vec3 specular;\n"
"    float strength;\n"
"};\n"
"uniform DirLight dirLight;\n"
"uniform bool useDirLight = false; // Set this to true to enable directional light\n"
"\n"
"struct PointLight {\n"
"    vec3 position;\n"
"    float strength;\n"
"\n"
"    vec3 ambient;\n"
"    vec3 diffuse;\n"
"    vec3 specular;\n"
"\n"
"    // Light attenuation\n"
"    float constant;\n"
"    float linear;\n"
"    float quadratic;\n"
"};\n"
"#define NR_POINT_LIGHTS 4\n"
"uniform PointLight pointLights[NR_POINT_LIGHTS];\n"
"uniform int nPointLights = 0; // Set this to the number of point lights you have\n"
"\n"
"uniform float transparency = 1.0;\n"
"\n"
"// inputs\n"
"in vec3 Normal;\n"
"in vec3 FragPos;\n"
"in vec2 TexCoords;\n"
"\n"
"// Uniforms\n"
"uniform vec3 viewPos;\n"
"\n"
"// Outputs\n"
"out vec4 FragColor; \n"
"\n"
"// Function prototypes\n"
"vec3 CalcDirLight(DirLight light, vec3 normal, vec3 viewDir);\n"
"vec3 CalcPointLight(PointLight light, vec3 normal, vec3 fragPos, vec3 viewDir);\n"
"\n"
"void main()\n"
"{\n"
"    vec4 textColor = texture(material.texture_diffuse1, TexCoords);\n"
"    if (textColor.a < 0.1) discard;\n"
"\n"
"    vec3 norm = normalize(Normal);\n"
"    vec3 viewDir = normalize(viewPos - FragPos);\n"
"\n"
"    vec3 result = vec3(0.0);\n"
"\n"
"    // Directional light\n"
"    if (useDirLight) {\n"
"        result = CalcDirLight(dirLight, norm, viewDir);\n"
"    }\n"
"    else {\n"
"        // If we don't have a directional light, just use the texture\n"
"        result = vec3(textColor);\n"
"    }\n"
"\n"
"    // Point lights\n"
"    if (nPointLights > 0) {\n"
"        for (int i = 0; i < NR_POINT_LIGHTS; i++) {\n"
"            if (i >= nPointLights) break;\n"
"            result += CalcPointLight(pointLights[i], norm, FragPos, viewDir);\n"
"        }\n"
"    }\n"
"\n"
"    // Output result\n"
"    FragColor = vec4(result, transparency);\n"
"}\n"
"\n"
"vec3 CalcDirLight(DirLight light, vec3 normal, vec3 viewDir) \n"
"{\n"
"    vec3 lightDir = normalize(-light.direction);\n"
"\n"
"    // diffuse shading\n"
"    float diff = max(dot(normal, lightDir), 0.0);\n"
"\n"
"    // specular shading\n"
"    vec3 reflectDir = reflect(-lightDir, normal);\n"
"    float spec = pow(max(dot(viewDir, reflectDir), 0.0), material.shininess );\n"
"\n"
"    // combine results\n"
"    vec3 ambient  = light.ambient  * vec3(texture(material.texture_diffuse1, TexCoords));\n"
"    vec3 diffuse  = light.diffuse  * diff * vec3(texture(material.texture_diffuse1, TexCoords));\n"
"    vec3 specular = light.specular * spec * vec3(texture(material.texture_specular1, TexCoords));\n"
"    return (ambient + diffuse + specular) * light.strength;\n"
"}\n"
"\n"
"vec3 CalcPointLight(PointLight light, vec3 normal, vec3 fragPos, vec3 viewDir)\n"
"{\n"
"    vec3 lightDir = normalize(light.position - fragPos);\n"
"\n"
"    // diffuse shading\n"
"    float diff = max(dot(normal, lightDir), 0.0);\n"
"\n"
"    // specular shading\n"
"    vec3 reflectDir = reflect(-lightDir, normal);\n"
"    float spec = pow(max(dot(viewDir, reflectDir), 0.0), material.shininess);\n"
"\n"
"    // attenuation\n"
"    float distance    = length(light.position - fragPos);\n"
"    float attenuation = 1.0 / (light.constant + light.linear * distance + \n"
"  			     light.quadratic * (distance * distance));\n"
"\n"
"    // combine results\n"
"    vec3 ambient  = light.ambient  * vec3(texture(material.texture_diffuse1, TexCoords));\n"
"    vec3 diffuse  = light.diffuse  * diff * vec3(texture(material.texture_diffuse1, TexCoords));\n"
"    vec3 specular = light.specular * spec * vec3(texture(material.texture_specular1, TexCoords));\n"
"    ambient  *= attenuation;\n"
"    diffuse  *= attenuation;\n"
"    specular *= attenuation;\n"
"    return (ambient + diffuse + specular) * light.strength;\n"
"}\n"
;
