static const char* mandelbrot_fs = "#version 400 core\n"
"\n"
"out vec4 FragColor;\n"
"in vec2 texCoords;\n"
"\n"
"uniform vec3 resolution;\n"
"uniform int maxIterations = 100;\n"
"uniform float zoom;\n"
"uniform vec3 offset;\n"
"uniform vec3 constant;\n"
"uniform bool juliaSet = false;\n"
"\n"
"float mandelbrot()\n"
"{\n"
"    vec2 startingPosition = vec2(0.2, 0.0);\n"
"\n"
"    // Normalized coordinates\n"
"    vec2 uv = (gl_FragCoord.xy - 0.3 * resolution.xy) / (resolution.y * 2.0);\n"
"    uv += startingPosition + offset.xy * pow(zoom, 4.0);\n"
"\n"
"    vec2 c = 5.0 * uv - vec2(0.7, 0.0);\n"
"    c = c / pow(zoom, 4.0) + vec2(0.4, 0.4);\n"
"    vec2 z = vec2(0.0);\n"
"    float iter = 0.0;\n"
"    float smoothIter = 0.0;\n"
"    for (int i = 0; i < maxIterations; i++)\n"
"    {\n"
"        z = vec2(z.x * z.x - z.y * z.y, 2.0 * z.x * z.y) + c;\n"
"        if (length(z) > 2.0)\n"
"        {\n"
"            smoothIter = iter + 1.0 - log(log(length(z))) / log(2.0);\n"
"            return smoothIter / float(maxIterations);\n"
"        }\n"
"        iter++;\n"
"    }\n"
"    return 0.0;\n"
"}\n"
"\n"
"float julia()\n"
"{\n"
"    vec2 startingPosition = vec2(0.2, 0.0);\n"
"\n"
"    // Normalized coordinates\n"
"    vec2 uv = (gl_FragCoord.xy - 0.3 * resolution.xy) / (resolution.y * 2.0);\n"
"    uv += startingPosition + offset.xy;\n"
"\n"
"    dvec2 z = 5.0 * uv - dvec2(0.7, 0.0);\n"
"    z = z / pow(zoom, 4.0) + vec2(0.4, 0.4);\n"
"\n"
"    float iterations = 0.0;\n"
"    float smoothIter = 0.0;\n"
"    while(iterations < maxIterations && length(z) < 2.0)\n"
"    {\n"
"        z = vec2(z.x * z.x - z.y * z.y, 2.0 * z.x * z.y) + constant.xy;\n"
"        iterations++;\n"
"    }\n"
"\n"
"    if (iterations >= maxIterations)\n"
"        return 0.0;\n"
"    smoothIter = iterations + 1.0 - log(log(float(length(z)))) / log(2.0);\n"
"    return smoothIter / maxIterations;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    float col = 0.0;\n"
"\n"
"    if (juliaSet)\n"
"        col = julia();\n"
"    else\n"
"        col = mandelbrot();\n"
"\n"
"    // Gamma correction\n"
"    col = pow(col, 0.5);\n"
"    col = 1.0 - cos(col * 3.14159265);\n"
"\n"
"    vec3 m = vec3(col, col * 0.5, col * 0.25); // Example of gradient mapping\n"
"    FragColor = vec4(m, 1.0);\n"
"}\n"
;
