static const char* mandelbrot_vs = "#version 330 core\n"
"\n"
"layout (location = 0) in vec2 inPos;\n"
"layout (location = 1) in vec2 inTexCoords;\n"
"\n"
"out vec2 texCoords;\n"
"\n"
"void main()\n"
"{\n"
"    gl_Position = vec4(inPos.x, inPos.y, 0.0, 1.0);\n"
"    texCoords = inTexCoords;\n"
"}\n"
;
