static const char* sharpen_kernel_vs = "#version 330 core\n"
"layout(location = 0) in vec3 aPos;\n"
"layout(location = 2) in vec2 aTexCoords;\n"
"\n"
"out vec2 TexCoords;\n"
"\n"
"void main()\n"
"{\n"
"  gl_Position = vec4(aPos, 1.0);\n"
"  TexCoords = aTexCoords;  // pass to fragment shader\n"
"}\n"
;
