static const char* sharpen_kernel_fs = "#version 330 core\n"
"\n"
"in vec2 TexCoords;\n"
"out vec4 FragColor;\n"
"\n"
"uniform sampler2D screenTexture;\n"
"\n"
"const float offset = 1.0 / 300.0;\n"
"\n"
"void main()\n"
"{\n"
"\n"
"  vec2 offsets[9] = vec2[](\n"
"                           vec2(-offset,  offset),\n"
"                           vec2( 0.0f,    offset),\n"
"                           vec2( offset,  offset),\n"
"                           vec2(-offset,  0.0f),\n"
"                           vec2( 0.0f,    0.0f),\n"
"                           vec2( offset,  0.0f),\n"
"                           vec2(-offset,  -offset),\n"
"                           vec2( 0.0f,    -offset),\n"
"                           vec2( offset,  -offset)\n"
"                           );\n"
"\n"
"  float kernel[9] = float[](\n"
"                            -1, -1, -1,\n"
"                            -1,  9, -1,\n"
"                            -1, -1, -1\n"
"                            );\n"
"\n"
"  vec3 sampleTex[9];\n"
"  for (int i = 0; i < 9; i++)\n"
"  {\n"
"    sampleTex[i] = vec3(texture(screenTexture, TexCoords.st + offsets[i]));\n"
"  }\n"
"  vec3 col = vec3(0.0);\n"
"  for (int i = 0; i < 9; i++)\n"
"    col += sampleTex[i] * kernel[i];\n"
"\n"
"  FragColor = vec4(col, 1.0);\n"
"}\n"
;
