// SPDX-License-Identifier: MIT
// Author:  Giovanni Santini
// Mail:    giovanni.santini@proton.me
// Github:  @San7o

#pragma once

#include <glad/glad.h> // OpenGL driver

namespace brenta
{

namespace types
{

/**
 * @brief Buffer wrapper around OpenGL buffer objects
 *
 * This class is a wrapper around OpenGL buffer objects. It provides a
 * simple interface to create, bind, unbind and delete buffer objects.
 */
class buffer
{
public:
  /**
   * @brief Buffer object id, generated by OpenGL
   */
  unsigned int id;
  /**
   * @brief Buffer object target (like GL_ARRAY_BUFFER,
   *        GL_ELEMENT_ARRAY_BUFFER...)
   */
  GLenum target;

  /**
   * @brief Default constructor, does nothing
   */
  buffer()
  {
  }

  buffer(GLenum input_target);

  constexpr buffer(const buffer&) = delete;
  constexpr buffer& operator=(const buffer&) = delete;
  
  constexpr buffer(buffer&& other) noexcept
  {
    this->id = other.id;
    this->target = other.target;
    other.id = 0;
  }
  constexpr buffer& operator=(buffer&& other) noexcept
  {
    this->id = other.id;
    this->target = other.target;
    other.id = 0;
    return *this;
  }

  ~buffer();
  
  void init(GLenum input_target);
  void destroy();
  void bind();
  void unbind();

  // Getters

  int get_id();
  GLenum get_target();

  // Setters

  void set_id(unsigned int id);
  void set_target(GLenum target);

  // Utilities

  /**
   * @brief Copy data to the buffer object
   *
   * @param size Size of the data in bytes
   * @param data Pointer to the data
   * @param usage OpenGL usage hint (like GL_STATIC_DRAW)
   */
  void copy_data(GLsizeiptr size, const void *data, GLenum usage);
  /**
   * @brief Copy data to the buffer object
   *
   * @param size Size of the data in bytes
   * @param data Pointer to the data
   * @param usage OpenGL usage hint (like GL_STATIC_DRAW)
   *
   * Same as copy_date() but for target GL_ARRAY_BUFFER. The naming is
   * more specific to the use case.
   */
  void copy_vertices(GLsizeiptr size, const void *data, GLenum usage);
  /**
   * @brief Copy data to the buffer object
   *
   * @param size Size of the data in bytes
   * @param data Pointer to the data
   * @param usage OpenGL usage hint (like GL_STATIC_DRAW)
   *
   * Same as copy_vertices() but for target GL_ELEMENT_ARRAY_BUFFER.
   */
  void copy_indices(GLsizeiptr size, const void *data, GLenum usage);
};

} // namespace types

} // namespace brenta
